/** @type {import('tailwindcss').Config} */
import colors from 'tailwindcss/colors';

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        primary: {
          25: 'hsl(var(--primary-25))',
          50: 'hsl(var(--primary-50))',
          100: 'hsl(var(--primary-100))',
          150: 'hsl(var(--primary-150))',
          200: 'hsl(var(--primary-200))',
          300: 'hsl(var(--primary-300))',
          400: 'hsl(var(--primary-400))',
          500: 'hsl(var(--primary-500))',
          600: 'hsl(var(--primary-600))',
          700: 'hsl(var(--primary-700))',
          800: 'hsl(var(--primary-800))',
          850: 'hsl(var(--primary-850))',
          900: 'hsl(var(--primary-900))',
          950: 'hsl(var(--primary-950))',
          975: 'hsl(var(--primary-975))',
          DEFAULT: 'hsl(var(--primary-500))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        warning: {
          25: 'hsl(var(--warning-25))',
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          150: 'hsl(var(--warning-150))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
          800: 'hsl(var(--warning-800))',
          850: 'hsl(var(--warning-850))',
          900: 'hsl(var(--warning-900))',
          950: 'hsl(var(--warning-950))',
          975: 'hsl(var(--warning-975))',
          DEFAULT: 'hsl(var(--warning-500))',
        },
        gray: {
          25: 'hsl(var(--gray-25))',
          50: 'hsl(var(--gray-50))',
          100: 'hsl(var(--gray-100))',
          150: 'hsl(var(--gray-150))',
          200: 'hsl(var(--gray-200))',
          300: 'hsl(var(--gray-300))',
          400: 'hsl(var(--gray-400))',
          500: 'hsl(var(--gray-500))',
          600: 'hsl(var(--gray-600))',
          700: 'hsl(var(--gray-700))',
          800: 'hsl(var(--gray-800))',
          850: 'hsl(var(--gray-850))',
          900: 'hsl(var(--gray-900))',
          950: 'hsl(var(--gray-950))',
          975: 'hsl(var(--gray-975))',
          1000: 'hsl(var(--gray-1000))',
          DEFAULT: 'hsl(var(--gray-500))',
        },
        neutral: {
          25: 'hsl(var(--neutral-25))',
          50: 'hsl(var(--neutral-50))',
          100: 'hsl(var(--neutral-100))',
          150: 'hsl(var(--neutral-150))',
          200: 'hsl(var(--neutral-200))',
          300: 'hsl(var(--neutral-300))',
          400: 'hsl(var(--neutral-400))',
          500: 'hsl(var(--neutral-500))',
          600: 'hsl(var(--neutral-600))',
          700: 'hsl(var(--neutral-700))',
          800: 'hsl(var(--neutral-800))',
          850: 'hsl(var(--neutral-850))',
          900: 'hsl(var(--neutral-900))',
          950: 'hsl(var(--neutral-950))',
          975: 'hsl(var(--neutral-975))',
          DEFAULT: 'hsl(var(--neutral-500))',
        },
        error: {
          25: 'hsl(var(--error-25))',
          50: 'hsl(var(--error-50))',
          100: 'hsl(var(--error-100))',
          150: 'hsl(var(--error-150))',
          200: 'hsl(var(--error-200))',
          300: 'hsl(var(--error-300))',
          400: 'hsl(var(--error-400))',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          700: 'hsl(var(--error-700))',
          800: 'hsl(var(--error-800))',
          850: 'hsl(var(--error-850))',
          900: 'hsl(var(--error-900))',
          950: 'hsl(var(--error-950))',
          975: 'hsl(var(--error-975))',
          DEFAULT: 'hsl(var(--error-500))',
        },
        success: {
          25: 'hsl(var(--success-25))',
          50: 'hsl(var(--success-50))',
          100: 'hsl(var(--success-100))',
          150: 'hsl(var(--success-150))',
          200: 'hsl(var(--success-200))',
          300: 'hsl(var(--success-300))',
          400: 'hsl(var(--success-400))',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          700: 'hsl(var(--success-700))',
          800: 'hsl(var(--success-800))',
          850: 'hsl(var(--success-850))',
          900: 'hsl(var(--success-900))',
          950: 'hsl(var(--success-950))',
          975: 'hsl(var(--success-975))',
          DEFAULT: 'hsl(var(--success-500))',
        },
        black: {
          8: 'hsl(var(--black-8))',
          16: 'hsl(var(--black-16))',
          24: 'hsl(var(--black-24))',
          32: 'hsl(var(--black-32))',
          40: 'hsl(var(--black-40))',
          48: 'hsl(var(--black-48))',
          56: 'hsl(var(--black-56))',
          64: 'hsl(var(--black-64))',
          72: 'hsl(var(--black-72))',
          80: 'hsl(var(--black-80))',
          88: 'hsl(var(--black-88))',
          96: 'hsl(var(--black-96))',
          100: 'hsl(var(--black-100))',
          DEFAULT: 'hsl(var(--black-100))',
        },
        white: {
          8: 'hsl(var(--white-8))',
          16: 'hsl(var(--white-16))',
          24: 'hsl(var(--white-24))',
          32: 'hsl(var(--white-32))',
          40: 'hsl(var(--white-40))',
          48: 'hsl(var(--white-48))',
          56: 'hsl(var(--white-56))',
          64: 'hsl(var(--white-64))',
          72: 'hsl(var(--white-72))',
          80: 'hsl(var(--white-80))',
          88: 'hsl(var(--white-88))',
          96: 'hsl(var(--white-96))',
          100: 'hsl(var(--white-100))',
          DEFAULT: 'hsl(var(--white-100))',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          background: 'hsla(var(--sidebar-background))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          hover: 'hsl(var(--sidebar-hover))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};